<?php
/**
 * 由 PhpStorm 创造.
 * 用户: Administrator朕之天下
 * 日期: 2018/6/19
 * 时间: 18:20
 */

namespace app\api\controller\v1;


use app\api\controller\BaseController;
use app\common\model\User;
use app\lib\exception\TokenException;
use think\Cache;

class BaseAuth extends BaseController
{
    /**
     * 用户信息
     * @var array
     */
    public $user = [];

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if(empty($this->isLogin())) {
            throw new TokenException([
                'msg' => '没有登录',
                'code' => 404
            ]);
        }
    }

    /**
     * 判断是否登录
     * @return bool
     */
    public function isLogin()
    {
        // 判断header是否有token
        if(empty($this->headers['token'])) {
            return false;
        }

//        // 判断缓存是否存在token
//        $token = Cache::get($this->headers['token']);
//        if (empty($token)){
//            return false;
//        }

        $user = User::get(['token' => $this->headers['token']]);

        // 判断用户存在且是否审核通过
        if(!$user || $user->status != 1) {
            return false;
        }
        // 判定时间是否过期
        if(time() > $user->time_out) {
            return false;
        }

        $this->user = $user;
        return true;

    }

}